#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_ADDR_SPACE_SIZE 1024 // in GiBs
#define CONFIG_BSP_BOOT_STACK_SIZE 0x1000
#define CONFIG_CPUS_MAX 16
#define CONFIG_KERNEL_ADDR 0x100000

#endif // CONFIG_H
