#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_ADDR_SPACE_SIZE ((uint64_t)1 << 40)
#define CONFIG_AP_BOOT_STACK_SIZE 0x1000
#define CONFIG_BSP_BOOT_STACK_SIZE 0x2000
#define CONFIG_CPUS_MAX 16
#define CONFIG_IDLE_STACK_SIZE 0x1000
#define CONFIG_ISR_STACK_SIZE 0x1000
#define CONFIG_KERNEL_ADDR 0x100000
#define CONFIG_SCHEDULER_PRIORITIES 8
#define CONFIG_SCHEDULER_TICK_INTERVAL 1000 // in microseconds

#endif // CONFIG_H
