#ifndef PAGE_MAP_H
#define PAGE_MAP_H

#include "config.h"
#include "sys_table.h"
#include "util.h"

#define PAGE_SIZE 0x200000

#define PAGE_MAP_PDS \
  SIZE_ELEMENTS(CONFIG_ADDR_SPACE_SIZE, SYS_PAGE_TABLE_DESCS * PAGE_SIZE)
#define PAGE_MAP_PDPTS \
  SIZE_ELEMENTS(PAGE_MAP_PDS, SYS_PAGE_TABLE_DESCS)
#define PAGE_MAP_SIZE \
  ((PAGE_MAP_PDS + PAGE_MAP_PDPTS + 1) * SYS_PAGE_TABLE_SIZE)

#endif // PAGE_MAP_H
